<?php

return [
    0 => ['name' => 'jobs.vagrant', 'rank' => null, 'minLvl' => 1, 'maxLvl' => 15, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    1 => ['name' => 'jobs.mercenary', 'rank' => null, 'minLvl' => 15, 'maxLvl' => 60, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    2 => ['name' => 'jobs.acrobat', 'rank' => null, 'minLvl' => 15, 'maxLvl' => 60, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    3 => ['name' => 'jobs.assist', 'rank' => null, 'minLvl' => 15, 'maxLvl' => 60, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    4 => ['name' => 'jobs.magician', 'rank' => null, 'minLvl' => 15, 'maxLvl' => 60, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    6 => ['name' => 'jobs.knight', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    7 => ['name' => 'jobs.blade', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    8 => ['name' => 'jobs.jeter', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    9 => ['name' => 'jobs.ranger', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    10 => ['name' => 'jobs.ringmaster', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    11 => ['name' => 'jobs.billposter', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    12 => ['name' => 'jobs.psykeeper', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    13 => ['name' => 'jobs.elementor', 'rank' => null, 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => null],
    16 => ['name' => 'jobs.knight_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    17 => ['name' => 'jobs.blade_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    18 => ['name' => 'jobs.jeter_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    19 => ['name' => 'jobs.ranger_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    20 => ['name' => 'jobs.ringmaster_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    21 => ['name' => 'jobs.billposter_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    22 => ['name' => 'jobs.psykeeper_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    23 => ['name' => 'jobs.elementor_m', 'rank' => 'Master', 'minLvl' => 60, 'maxLvl' => 120, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Export%d.png'],
    24 => ['name' => 'jobs.knight_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    25 => ['name' => 'jobs.blade_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    26 => ['name' => 'jobs.jeter_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    27 => ['name' => 'jobs.ranger_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    28 => ['name' => 'jobs.ringmaster_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    29 => ['name' => 'jobs.billposter_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    30 => ['name' => 'jobs.psykeeper_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    31 => ['name' => 'jobs.elementor_h', 'rank' => 'Hero', 'minLvl' => 121, 'maxLvl' => 130, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Hero.png'],
    32 => ['name' => 'jobs.templar', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    33 => ['name' => 'jobs.slayer', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    34 => ['name' => 'jobs.harlequin', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    35 => ['name' => 'jobs.crackshooter', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    36 => ['name' => 'jobs.seraph', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    37 => ['name' => 'jobs.force_master', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    38 => ['name' => 'jobs.mentalist', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
    39 => ['name' => 'jobs.arcanist', 'rank' => 'Legend', 'minLvl' => 130, 'maxLvl' => 150, 'imageJob' => '/images/jobs/%d.png', 'imageLvl' => '/images/jobs/icon_Legend.png'],
];