<?php

return [
	 0 => ['name' => 'site.jobs.vagrant', 		'rank' => null, 		'minLvl' => 1, 		'maxLvl' => 15,		'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 1 => ['name' => 'site.jobs.mercenary', 	'rank' => null, 		'minLvl' => 15, 	'maxLvl' => 60,		'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 2 => ['name' => 'site.jobs.acrobat', 		'rank' => null, 		'minLvl' => 15, 	'maxLvl' => 60,		'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 3 => ['name' => 'site.jobs.assist', 		'rank' => null, 		'minLvl' => 15, 	'maxLvl' => 60,		'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 4 => ['name' => 'site.jobs.magician', 		'rank' => null, 		'minLvl' => 15, 	'maxLvl' => 60,		'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 6 => ['name' => 'site.jobs.knight', 		'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 7 => ['name' => 'site.jobs.blade', 		'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 8 => ['name' => 'site.jobs.jeter', 		'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	 9 => ['name' => 'site.jobs.ranger', 		'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	10 => ['name' => 'site.jobs.ringmaster', 	'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	11 => ['name' => 'site.jobs.billposter', 	'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	12 => ['name' => 'site.jobs.psykeeper', 	'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	13 => ['name' => 'site.jobs.elementor', 	'rank' => null, 		'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => null],
	16 => ['name' => 'site.jobs.knight_m', 		'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	17 => ['name' => 'site.jobs.blade_m', 		'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	18 => ['name' => 'site.jobs.jeter_m', 		'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	19 => ['name' => 'site.jobs.ranger_m', 		'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	20 => ['name' => 'site.jobs.ringmaster_m', 	'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	21 => ['name' => 'site.jobs.billposter_m', 	'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	22 => ['name' => 'site.jobs.psykeeper_m', 	'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	23 => ['name' => 'site.jobs.elementor_m', 	'rank' => 'Master', 	'minLvl' => 60, 	'maxLvl' => 120,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Export%d.png'],
	24 => ['name' => 'site.jobs.knight_h', 		'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	25 => ['name' => 'site.jobs.blade_h', 		'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	26 => ['name' => 'site.jobs.jeter_h', 		'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	27 => ['name' => 'site.jobs.ranger_h', 		'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	28 => ['name' => 'site.jobs.ringmaster_h', 	'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	29 => ['name' => 'site.jobs.billposter_h', 	'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	30 => ['name' => 'site.jobs.psykeeper_h', 	'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	31 => ['name' => 'site.jobs.elementor_h', 	'rank' => 'Hero', 		'minLvl' => 121, 	'maxLvl' => 130,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Hero.png'],
	32 => ['name' => 'site.jobs.templar', 		'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	33 => ['name' => 'site.jobs.slayer', 		'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	34 => ['name' => 'site.jobs.harlequin', 	'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	35 => ['name' => 'site.jobs.crackshooter', 	'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	36 => ['name' => 'site.jobs.seraph', 		'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	37 => ['name' => 'site.jobs.force_master', 	'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	38 => ['name' => 'site.jobs.mentalist', 	'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
	39 => ['name' => 'site.jobs.arcanist', 		'rank' => 'Legend', 	'minLvl' => 130, 	'maxLvl' => 150,	'imageJob' => '/img/jobs/%d.png', 'imageLvl' => '/img/jobs/icon_Legend.png'],
];